name: JMurmel Native Image builds

on:
  push:
    paths-ignore:
      - CHANGES
      - "**.md"
      - "**.txt"
      - "**.html"
      - "**.lisp"
      - "**.completions"
      - "scribbles/**"

env:
  JAVA_VERSION: 21

jobs:
  build:
    name: JMurmel Native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Restore Maven repo
        id: restore-maven
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-graalvm-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build JMurmel
        run: |
          mvn -V -B clean package -pl lambda "-Djavac.target=${{ env.JAVA_VERSION }}" -DskipTests
          mvn -V -B clean package -f graalvm/pom.xml "-Djavac.target=${{ env.JAVA_VERSION }}" -DskipTests

      - name: Run native image Windows
        if: "${{ runner.os }}" = "Windows"
        run: |
          native-image --no-fallback --initialize-at-build-time=io.github.jmurmel -H:IncludeResources="META-INF/.*" -H:ReflectionConfigurationFiles=./graalvm/src/main/graalvm/reflectconfig -H:DynamicProxyConfigurationFiles=./graalvm/src/main/graalvm/proxyconfig -cp ./graalvm/target/unsupported.jar -jar ./lambda/target/jmurmel.jar
          ./jmurmel --version

      - name: Run native image Linux
        if: "${{ runner.os }}" = "Linux"
        run: |
          native-image --gc=G1 --no-fallback --initialize-at-build-time=io.github.jmurmel -H:IncludeResources="META-INF/.*" -H:ReflectionConfigurationFiles=./graalvm/src/main/graalvm/reflectconfig -H:DynamicProxyConfigurationFiles=./graalvm/src/main/graalvm/proxyconfig -cp ./graalvm/target/unsupported.jar -jar ./lambda/target/jmurmel.jar
          ./jmurmel --version

      - name: Save Maven repo
        id: cache-maven
        uses: actions/cache/save@v3
        with:
          path: ~/.m2/repository
          key: ${{ steps.restore-maven.outputs.cache-primary-key }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ runner.os }}-${{ runner.arch }}
          path: |
            jmurmel
            jmurmel.exe
            murmel-langref.md
            mlib.md
            murmel-langref.html
            mlib.html
            LICENSE

      - name: Upload mlib
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ runner.os }}-${{ runner.arch }}
          path: |
            samples.mlib/mlib.lisp
