name: JMurmel Native Image builds

on:
  push:
    paths-ignore:
      - CHANGES
      - "**.md"
      - "**.txt"
      - "**.html"
      - "**.lisp"
      - "**.completions"
      - "scribbles/**"

env:
  JAVA_VERSION: 17
  GRAAL_VERSION: 22.3.1

jobs:
  build:
    name: JMurmel Native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ env.GRAAL_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache Maven packages
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run JMurmel
        run: |
          java --version
          mvn -B clean package -pl lambda "-Djavac.target=${{ env.JAVA_VERSION }}" -DskipTests
          native-image --report-unsupported-elements-at-runtime -H:IncludeResources="META-INF/.*" -H:ReflectionConfigurationFiles=./lambda/src/main/graalvm/reflectconfig -H:DynamicProxyConfigurationFiles=./lambda/src/main/graalvm/proxyconfig -jar lambda/target/jmurmel.jar
          ./jmurmel --version

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ runner.os }}-${{ runner.arch }}
          path: |
            jmurmel
            jmurmel.exe
            murmel-langref.md
            mlib.md
            murmel-langref.html
            mlib.html
            LICENSE

      - name: Upload mlib
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ runner.os }}-${{ runner.arch }}
          path: |
            samples.mlib/mlib.lisp
