name: JMurmel Native Image builds

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "**.html"
      - "**.completions"
      - "scribbles/**"

jobs:
  build:
    name: JMurmel Native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run JMurmel
        run: |
          java --version
          mvn -B clean package -pl lambda -DskipTests -Djavac.target=17
          native-image --report-unsupported-elements-at-runtime -H:IncludeResources="META-INF/.*" -H:ReflectionConfigurationFiles=./lambda/src/main/graalvm/reflectconfig -H:DynamicProxyConfigurationFiles=./lambda/src/main/graalvm/proxyconfig -jar lambda/target/jmurmel.jar
          ./jmurmel --version

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ matrix.os }}
          path: |
            jmurmel
            jmurmel.exe
            murmel-langref.html
            mlib.html
            LICENSE

      - name: Upload mlib
        uses: actions/upload-artifact@v3
        with:
          name: jmurmel-native-${{ runner.os }}-${{ runner.arch }}
          path: |
            samples.mlib/mlib.lisp
