# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java8/17/19/20-ea CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "**.html"
      - "**.completions"
      - "scribbles/**"
    branches: [ master ]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "**.html"
      - "**.completions"
      - "scribbles/**"
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '17', '19', '20-ea' ]
    name: Java ${{ matrix.Java }} CI

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean install site --file pom.xml -Djdk.console=jdk.jshell -Djavac.target=`echo "${{ matrix.java }}" | sed -e "s/-ea//g"`

    - name: Upload Jar
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-zulu-${{ matrix.java }}
        path: |
          lambda/target/jmurmel.jar

    - name: Upload docs
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-zulu-${{ matrix.java }}
        path: |
          murmel-langref.md
          mlib.md
          murmel-langref.html
          mlib.html
          LICENSE

    - name: Upload mlib
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-zulu-${{ matrix.java }}
        path: |
          samples.mlib/mlib.lisp


    - name: Create W64 launcher
      if: ${{ matrix.java == '8' }}
      run: mvn -B package -pl scripts -Dlaunch4j.skip=false

    - name: Upload launch4j exe
      if: ${{ matrix.java == '8' }}
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-w64-slim
        path: |
          scripts/target/jmurmel.exe

    - name: Upload launch4j mlib
      if: ${{ matrix.java == '8' }}
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-w64-slim
        path: |
          samples.mlib/mlib.lisp

    - name: Upload launch4j docs
      if: ${{ matrix.java == '8' }}
      uses: actions/upload-artifact@v3
      with:
        name: jmurmel-w64-slim
        path: |
          murmel-langref.md
          mlib.md
          murmel-langref.html
          mlib.html
          LICENSE
          legal/launch4j/*
