# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# When a tag is pushed then also create a release,
# see https://github.com/softprops/action-gh-release

name: Create release

on:
  push:
    tags: "jmurmel-all*"

env:
  JAVA_VERSION: 8
  JAVA_TARGET: 8

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest
    name: Release

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'zulu'

    - name: Restore Maven repo
      uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      run: mvn -V -B clean package -pl lambda,scripts -Dlaunch4j.skip=false -DskipTests=true -Djavac.target=${{ env.JAVA_TARGET }}

    - name: Create Jar zipfile
      run: zip -j ${{ github.ref_name }}-jar.zip      LICENSE lambda/target/jmurmel.jar  samples.mlib/mlib.lisp murmel-langref.md murmel-langref.html mlib.md mlib.html

    - name: Create slim zipfile
      run: zip -j ${{ github.ref_name }}-w64-slim.zip LICENSE scripts/target/jmurmel.exe samples.mlib/mlib.lisp murmel-langref.md murmel-langref.html mlib.md mlib.html && zip -r ${{ github.ref_name }}-w64-slim.zip legal/launch4j/

    - name: Create release and upload files
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        prerelease: true
        files: |
          CHANGES
          GETTING STARTED.txt
          LICENSE
          lambda/target/jmurmel.jar
          samples.mlib/mlib.lisp
          mlib.md
          mlib.html
          murmel-langref.html
          murmel-langref.md
          ${{ github.ref_name }}-jar.zip
          ${{ github.ref_name }}-w64-slim.zip
